//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quinta.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lista_jugadoresEntities1 : DbContext
    {
        public lista_jugadoresEntities1()
            : base("name=lista_jugadoresEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<estado_usuario> estado_usuario { get; set; }
        public virtual DbSet<jugadores> jugadores { get; set; }
        public virtual DbSet<tipo_usuario1> tipo_usuario1 { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
