//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quinta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string clave { get; set; }
        public string mail { get; set; }
        public int id_estado { get; set; }
        public int id_tipo { get; set; }
    
        public virtual estado_usuario estado_usuario { get; set; }
        public virtual tipo_usuario1 tipo_usuario1 { get; set; }
    }
}
